//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneTaxiVisualization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identity_Smaller
    {
        public int ID { get; set; }
        public System.DateTime pickup_datetime { get; set; }
        public System.DateTime dropoff_datetime { get; set; }
        public string passenger_count { get; set; }
        public string trip_time_in_secs { get; set; }
        public string trip_distance { get; set; }
        public decimal pickup_longitude { get; set; }
        public decimal pickup_latitude { get; set; }
        public decimal dropoff_longitude { get; set; }
        public decimal dropoff_latitude { get; set; }
        public string fare_amount { get; set; }
        public string tip_amount { get; set; }
        public string tolls_amount { get; set; }
        public string total_amount { get; set; }
        public System.Data.Entity.Spatial.DbGeography pickup_geolocation { get; set; }
        public System.Data.Entity.Spatial.DbGeography dropoff_geolocation { get; set; }
    }
}
