//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneTaxiVisualization
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TaxiDataEntities : DbContext
    {
        public TaxiDataEntities()
            : base("name=TaxiDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Identity_Smaller> Identity_Smaller { get; set; }
    
        public virtual ObjectResult<RegionQueryPoly_Result> RegionQueryPoly(Nullable<System.DateTime> startDateTime, Nullable<System.DateTime> endDateTime, string polygonAsText, Nullable<int> pickDropBoth)
        {
            var startDateTimeParameter = startDateTime.HasValue ?
                new ObjectParameter("startDateTime", startDateTime) :
                new ObjectParameter("startDateTime", typeof(System.DateTime));
    
            var endDateTimeParameter = endDateTime.HasValue ?
                new ObjectParameter("endDateTime", endDateTime) :
                new ObjectParameter("endDateTime", typeof(System.DateTime));
    
            var polygonAsTextParameter = polygonAsText != null ?
                new ObjectParameter("polygonAsText", polygonAsText) :
                new ObjectParameter("polygonAsText", typeof(string));
    
            var pickDropBothParameter = pickDropBoth.HasValue ?
                new ObjectParameter("pickDropBoth", pickDropBoth) :
                new ObjectParameter("pickDropBoth", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RegionQueryPoly_Result>("RegionQueryPoly", startDateTimeParameter, endDateTimeParameter, polygonAsTextParameter, pickDropBothParameter);
        }
    }
}
